---
name: dnsmasq by zqsd
version: 0.1.16
slug: dnsmasq.zqsd
description: dnsmasq server because official one doesnt fit me
arch: [armhf, armv7, aarch64, amd64, i386]
url: https://github.com/zqsd1/ha-dnsmasq
startup: system
boot: auto
host_network: true
apparmor: true
host_dbus: true
privileged:
  - NET_ADMIN
init: false

options:
  dry_run: false
  log_level: info
  ssid:
  password:
  ip_cidr: 192.168.99.1/24
  interface: wlan0
  hidden: false
  enable_dns: false
  enable_nftables: false
  dns_server: 1.1.1.1
  override_dns: true
  spy_network: true
schema:
  dry_run: bool
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  ssid: match(^.{2,32}$)
  password: password
  ip_cidr: str
  interface: str
  hidden: bool
  enable_dns: bool
  enable_nftables: bool
  dns_server: str
  override_dns: bool
  spy_network: bool