---
name: dnsmasq by zqsd
version: 0.1.4
slug: dnsmasq.zqsd
description: dnsmasq server because official one doesnt fit me
arch: [armhf, armv7, aarch64, amd64, i386]
url: https://github.com/zqsd1/ha-dnsmasq
startup: system
boot: auto
host_network: true
apparmor: true
host_dbus: true
privileged:
  - NET_ADMIN
init: false

options:
  dry_run: false
  log_level: info
schema:
  dry_run: bool
  log_level: list(trace|debug|info|notice|warning|error|fatal)?