#!/usr/sbin/nft -f

table inet filter_haap_zqsd {
    chain forward {
        type filter hook forward priority -10;
        policy accept;

        iifname "wlan0" oifname "end0" accept
        iifname "end0" oifname "wlan0" ct state related,established accept
    }
}

table ip haap_zqsd {
    chain postrouting {
        type nat hook postrouting priority 100;

        ip saddr 192.168.99.0/24 oifname "end0" masquerade
    }
}