#!/usr/sbin/nft -f

table inet filter_haap_zqsd {
    chain input {
        type filter hook input priority 0;
        policy accept;
    }


    chain forward { 
        type filter hook forward priority filter;
        policy accept; 
    }
    
    chain output {
        type filter hook output priority 0;
        policy accept;
    }
}


table ip haap_zqsd {
    chain postrouting {
        type nat hook postrouting priority srcnat; 
        policy accept;

        oifname end0 masquerade
    }
}