---
name: ntopng
version: "1.0.1"
slug: ntopng
description: Network traffic monitoring using ntopng
startup: services
boot: auto
arch: [aarch64, amd64]
host_network: true
privileged:
  - NET_ADMIN
  - NET_RAW


options: 
  interface: wlan0

schema: 
  interface: str
